import { defineStore } from 'pinia';

export const useHiveStore = defineStore({
  id: 'hive-store',
  state: () => {
    return {
      accountType: '',
      activeUser: '',
      userData: {},
      systemLanguage: '',
      accessToken: '',
      routeState: '',
      countries: [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        "Côte d'Ivoire",
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo (Congo-Brazzaville)',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czechia (Czech Republic)',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        "Eswatini (fmr. 'Swaziland')",
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Holy See',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar (formerly Burma)',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'North Korea',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine State',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Korea',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Syria',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States of America',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela',
        'Vietnam',
        'Yemen',
        'Zambia',
        'Zimbabwe',
      ],

      ethnic: [
        'Akan',
        'Amhara',
        'Arab',
        'Armenian',
        'Ashanti',
        'Assyrian',
        'Aymara',
        'Bamar',
        'Baloch',
        'Bantu',
        'Bashkir',
        'Basque',
        'Bengali',
        'Berber',
        'Beti',
        'Bulgarian',
        'Buryat',
        'Cantonese',
        'Catalan',
        'Cherokee',
        'Chechen',
        'Chewa',
        'Chickasaw',
        'Chinese',
        'Chuvash',
        'Coptic',
        'Cree',
        'Croat',
        'Czech',
        'Danish',
        'Dutch',
        'English',
        'Estonian',
        'Fijian',
        'Finnish',
        'Flemish',
        'French',
        'Frisian',
        'Fula',
        'Galician',
        'Georgian',
        'German',
        'Greek',
        'Gujarati',
        'Haitian',
        'Han Chinese',
        'Hausa',
        'Hebrew',
        'Hindu',
        'Hmong',
        'Hungarian',
        'Iban',
        'Ibo',
        'Icelandic',
        'Igbo',
        'Inuit',
        'Irish',
        'Italian',
        'Japanese',
        'Javanese',
        'Kannada',
        'Kazakh',
        'Kikuyu',
        'Korean',
        'Kurdish',
        'Lao',
        'Latvian',
        'Lithuanian',
        'Luo',
        'Macedonian',
        'Malagasy',
        'Malay',
        'Malayalam',
        'Maldivian',
        'Mandinka',
        'Marathi',
        'Maori',
        'Mapuche',
        'Maya',
        'Mende',
        'Mestizo',
        'Mongol',
        'Montenegrin',
        'Ndebele',
        'Nepali',
        'Norwegian',
        'Oromo',
        'Pakistani',
        'Pashtun',
        'Persian',
        'Polish',
        'Portuguese',
        'Punjabi',
        'Quechua',
        'Romani',
        'Romanian',
        'Russian',
        'Samoan',
        'Sardinian',
        'Scottish',
        'Serbian',
        'Shona',
        'Sicilian',
        'Sindhi',
        'Sinhalese',
        'Slovak',
        'Slovene',
        'Somali',
        'Sotho',
        'Spanish',
        'Swahili',
        'Swazi',
        'Swedish',
        'Tajik',
        'Tamil',
        'Tatar',
        'Telugu',
        'Thai',
        'Tibetan',
        'Tongan',
        'Tswana',
        'Turkish',
        'Turkmen',
        'Ukrainian',
        'Urdu',
        'Uyghur',
        'Uzbek',
        'Vietnamese',
        'Welsh',
        'Xhosa',
        'Yoruba',
        'Zulu',
        'Caucasian',
        'others',
      ],
      languages: [
        'Afrikaans',
        'Albanian',
        'Amharic',
        'Arabic',
        'Armenian',
        'Assamese',
        'Azerbaijani',
        'Bambara',
        'Basque',
        'Belarusian',
        'Bengali',
        'Bosnian',
        'Bulgarian',
        'Burmese',
        'Catalan',
        'Cebuano',
        'Chewa',
        'Chinese',
        'Croatian',
        'Czech',
        'Danish',
        'Dutch',
        'English',
        'Esperanto',
        'Estonian',
        'Ewe',
        'Faroese',
        'Fijian',
        'Filipino',
        'Finnish',
        'French',
        'Fulah',
        'Galician',
        'Georgian',
        'German',
        'Greek',
        'Gujarati',
        'Haitian Creole',
        'Hausa',
        'Hawaiian',
        'Hebrew',
        'Hindi',
        'Hmong',
        'Hungarian',
        'Icelandic',
        'Igbo',
        'Indonesian',
        'Irish',
        'Italian',
        'Japanese',
        'Javanese',
        'Kannada',
        'Kazakh',
        'Khmer',
        'Kinyarwanda',
        'Kirundi',
        'Korean',
        'Kurdish',
        'Kyrgyz',
        'Lao',
        'Latvian',
        'Lingala',
        'Lithuanian',
        'Luxembourgish',
        'Macedonian',
        'Malagasy',
        'Malay',
        'Malayalam',
        'Maltese',
        'Mandarin',
        'Marathi',
        'Mongolian',
        'Nepali',
        'Norwegian',
        'Odia',
        'Oromo',
        'Pashto',
        'Persian',
        'Polish',
        'Portuguese',
        'Punjabi',
        'Quechua',
        'Romanian',
        'Russian',
        'Samoan',
        'Scots Gaelic',
        'Serbian',
        'Sesotho',
        'Shona',
        'Sindhi',
        'Sinhala',
        'Slovak',
        'Slovenian',
        'Somali',
        'Spanish',
        'Sundanese',
        'Swahili',
        'Swedish',
        'Tagalog',
        'Tajik',
        'Tamil',
        'Tatar',
        'Telugu',
        'Thai',
        'Tigrinya',
        'Tongan',
        'Turkish',
        'Turkmen',
        'Ukrainian',
        'Urdu',
        'Uyghur',
        'Uzbek',
        'Vietnamese',
        'Welsh',
        'Wolof',
        'Xhosa',
        'Yiddish',
        'Yoruba',
        'Zulu',
      ],
      services: [
        'others',
        'Woodworking',
        'Metalworking',
        'Pottery and Ceramics',
        'Textile and Fiber Arts',
        'Glassblowing',
        'Leatherworking',
        'Jewelry and Metalwork',
        'Painting and Drawing',
        'Sculpture',
        'Photography',
        'Candle Making',
        'Soap Making',
        'Basket Weaving',
        'Calligraphy and Hand Lettering',
        'Paper Crafts',
        'Beadwork and Jewelry Design',
        'Candlestick Making',
        'Wood Carving',
        'Blacksmithing',
        'Stained Glass Crafting',
        'Embroidery and Needlework',
        'Knitting and Crochet',
        'Quilting',
        'Pottery Wheel Classes',
        'Metal Sculpture Crafting',
        'Leather Tooling',
        'Engraving and Etching',
        'Stone Setting',
        'Oil Painting',
        'Watercolor Painting',
        'Charcoal and Pencil Drawing',
        'Clay Sculpture',
        'Bronze Casting',
        'Portrait Photography',
        'Event Photography',
        'Landscape Photography',
        'Product Photography',
        'Handmade Jewelry',
        'Custom Furniture Making',
        'Handwoven Textiles',
        'Handcrafted Leather Goods',
        'Artistic Glass Sculptures',
        'Handmade Pottery',
        'Custom Metal Jewelry Making',
        'Handmade Candles',
        'Artisan Soaps',
        'Basket Design and Weaving',
        'Custom Calligraphy Designs',
        'Handmade Greeting Cards',
        'Beadwork Jewelry',
        'Handmade Wooden Candlesticks',
        'Wooden Toy Crafting',
        'Metal Fabrication',
        'Custom Ceramic Tile Design',
        'Fabric Dyeing',
        'Leather Bag Making',
        'Jewelry Repair and Restoration',
        'Mural Painting',
        'Mixed Media Sculpture',
        'Public Art Installations',
        'Fine Art Photography Prints',
        'Handcrafted Pottery Dinnerware Sets',
        'Custom Leather Belts and Accessories',
        'Mechanic',
        'Carpenter',
        'Electrician',
        'Plumber',
        'Painter',
        'Mason',
        'Landscaper',
        'Interior Designer',
        'Graphic Designer',
        'Web Developer',
        'Computer Repair Technician',
        'Tailor and Seamstress',
        'Chef and Caterer',
        'Event Planner',
        'Hair Stylist and Barber',
        'Makeup Artist',
        'Personal Trainer',
        'Yoga Instructor',
        'Massage Therapist',
        'Life Coach',
        'Tutor',
        'Language Translator',
        'Financial Advisor',
        'Real Estate Agent',
        'Architect',
        'Surveyor',
        'Civil Engineer',
        'Mechanical Engineer',
        'Electrical Engineer',
        'Software Engineer',
        'Data Analyst',
        'Market Researcher',
        'Content Writer',
        'Social Media Manager',
        'Video Editor',
        'Animator',
        'Sound Engineer',
        'Event DJ',
        'Wedding Officiant',
        'Pet Groomer',
        'Dog Trainer',
        'Veterinarian',
        'Childcare Provider',
        'House Cleaner',
        'Personal Assistant',
        'Security Guard',
      ],
    };
  },
  actions: {
    SetActiveUser(id, set) {
      let name = 'activeroomuser';
      if (set) {
        this.activeUser = id;
        localStorage.setItem(name, id);
      } else {
        this.activeUser = '';
      }
    },
    SetUserData(data) {
      this.userData = data;
    },
    SetSystemLang(data) {
      this.systemLanguage = data;
      localStorage.setItem('systemLang', data);
    },
    SetAccessToken(token) {
      this.accessToken = token;
    },
    SetAccountType(data) {
      this.userData = data;
    },
    SetRouteState(name) {
      this.routeState = name;
    },
  },
  getters: {
    // filtersList: state => state.filtersList,
  },
});
